config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  include BlockEditor::Listable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.active_block_list.listable = @post

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, active_block_list_attributes: [ :id, :content ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Block Editor - Ruby on Rails - Sample</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="turbolinks-visit-control" content="reload">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'block_editor/application', 'data-turbolinks-track': 'reload', webpacker: 'BlockEditor' %>
    <%= stylesheet_pack_tag 'block_editor/application', 'data-turbolinks-track': 'reload', webpacker: 'BlockEditor' %>
  </head>

  <body>
    <header class="p-3 bg-dark text-white">
      <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
          <h1><a href="/" class="text-white navbar-brand">Ruby on Rails Block Editor</a></h1>
          <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          </ul>

          <div class="text-end">
            <% if action_name == "show" %>
              <a href="<%= edit_post_url(@post) %>" class="btn btn-outline-warning">Edit content</a>
            <% end %>
            <a href="/posts/new" class="btn btn-outline-light">Test it yourself</a>
            <a href="https://github.com/yamasolutions/block-editor" class="btn btn-primary" target="_blank">GitHub</a>
          </div>
        </div>
      </div>
    </header>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>

    <%= form.text_field :title %>
    <p class=form-text>A title isn't required but if you're wanting to find the content on the homepage it's useful</p>
  </div>
  <div class="alert alert-warning">
    <p>Image uploading is disabled - instead a random image will be selected from <a href="https://unsplash.com/" target="_blank">Unsplash</a></p>
  </div>


  <%= form.fields_for :active_block_list do |block_list| %>
    <%= BlockEditor::Instance.render(block_list) %>
  <% end %>

  <div class="actions">
    <%= form.submit nil, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="container mt-4">
  <h2>Editing Post</h2>
  <hr />

  <%= render 'form', post: @post %>
</div>

app/views/posts/index.html.erb
<div class="container mt-4">

  <p>This is a simple demonstration application to showcase <a href="https://github.com/yamasolutions/block-editor" target="_blank" class="">Block Editor</a>, a Ruby on Rails gem for creating rich content built using the <a href="https://github.com/WordPress/gutenberg" target="_blank">Wordpress Gutenberg</a> packages.</p>
  <p><a href="/posts/new" class="btn btn-primary">Test it yourself</a></p>

  <hr />
  <h2>User generated content</h2>
  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td><%= post.title %></td>
          <td><%= link_to 'Show', post %></td>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
          <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/posts/new.html.erb
<div class="container mt-4">
  <h2>New Post</h2>
  <hr />

  <%= render 'form', post: @post %>
</div>

app/views/posts/show.html.erb
<%= BlockEditor::BlockListRenderer.render(@post.active_block_list.content) %>